name: $(Date:yyyyMMdd)$(Rev:.r)

trigger: # cause a pipeline to run whenever you push an update to the specified branches
  batch: true
  branches:
    include:
      - main

parameters:
- name: Publish
  displayName: Push to public npm feed?
  type: boolean
  default: false

variables:
  TeamName: 'Visual Studio Technical Insights'

# The `resources` specify the location and version of the 1ES PT.
resources:
  repositories:
  - repository: MicrobuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/heads/release

extends:
  # The pipeline extends the 1ES PT which will inject different SDL and compliance tasks.
  # For non-production pipelines, use "Unofficial" as defined below.
  # For productions pipelines, use "Official".
  template: /azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    customBuildTags:
    - Ignore-Tag
    pool:
      name: VSEngSS-MicroBuild2022-1ES
      os: windows  # OS of the image. Allowed values: windows, linux, macOS
    
    stages:
    - stage: Test
      jobs:
      - job: Test
        displayName: Test

        steps:
        - task: GoTool@0
          inputs:
            version: 1.22.0
          displayName: 'Use Go 1.22.0'

        - task: Go@0
          inputs:
            command: test
            arguments: '-v .'
          displayName: Run Tests

        # Because there is no build and no build scanning is enabled, there are no TSA files to upload.
        # Commenting this out for now.
        # - task: TSAUpload@2
        #   inputs:
        #     GdnPublishTsaOnboard: true
        #     GdnPublishTsaConfigFile: '$(Build.SourcesDirectory)/.config/TSAOptions.json'
        #   displayName: 'TSA upload to Codebase (go-deviceid)'
